// Two spells per specialty: a utility technique and an advanced battlefield tool.
// Stable IDs keep talent purchases and three-slot loadouts compatible with saves.
const s = (name, kind, desc, cooldown, kit = {}) => ({
  name,
  kind,
  desc,
  cooldown,
  ...kit,
});
const rows = {
  cinder: [
    s(
      "Combustion sigil",
      "trap",
      "Plant a burning seal. Nearby prey trigger its eruption.",
      18,
      { element: "fire", radius: 155 },
    ),
    s(
      "Meteor procession",
      "meteor",
      "Three falling suns burn a path through the horde.",
      34,
      { element: "fire", count: 3, radius: 150 },
    ),
    s(
      "Solar dash",
      "charge",
      "Rush through foes and leave a burning wake.",
      18,
      { element: "fire", distance: 240 },
    ),
    s(
      "Flame orbit",
      "barrage",
      "A moving corona repeatedly launches piercing embers.",
      32,
      { element: "fire", projectile: "ember", count: 8 },
    ),
    s(
      "Ash barrier",
      "ward",
      "Raise an ember ward; blast nearby foes and regain heat.",
      24,
      { element: "fire", shield: 22, resource: 0.2 },
    ),
    s(
      "Rekindling rite",
      "field",
      "A fire sanctuary mends you through landed scorch pulses.",
      38,
      { element: "fire", mend: 0.025, follow: true },
    ),
  ],
  briar: [
    s(
      "Bramble pod",
      "trap",
      "A thorn pod roots prey and grows a guardian seedling.",
      20,
      { element: "garden", root: 1.2, plants: 1 },
    ),
    s(
      "Entangling grove",
      "field",
      "Raise a grove that repeatedly roots lesser foes.",
      34,
      { element: "garden", root: 0.8, plants: 3 },
    ),
    s(
      "Venom bloom",
      "field",
      "A distant spore bloom poisons and exposes its victims.",
      20,
      { element: "garden", dot: true, expose: 0.12 },
    ),
    s(
      "Spore migration",
      "barrage",
      "Walk with a cloud of piercing thorns and spreading venom.",
      32,
      { element: "garden", projectile: "thorn", dot: true },
    ),
    s(
      "Living bark",
      "ward",
      "Bark armor repels prey and shelters your garden.",
      24,
      { element: "garden", shield: 24, guard: 0.12 },
    ),
    s(
      "Life bond",
      "field",
      "A healing grove follows you; landed pulses mend its keeper.",
      38,
      { element: "garden", mend: 0.025, follow: true, plants: 2 },
    ),
  ],
  nyx: [
    s(
      "Blood fan",
      "fan",
      "Piercing knives expose prey to your next strikes.",
      16,
      { projectile: "knife", expose: 0.15, count: 5 },
    ),
    s(
      "Reaper dance",
      "blink",
      "Blink to prey, cut a wide circle and leave two echoes.",
      30,
      { shadows: 2, radius: 230, distance: 300 },
    ),
    s(
      "Veil step",
      "blink",
      "Cross the veil; gain a brief escape window and an echo.",
      20,
      { shadows: 1, distance: 230, guard: 0.12 },
    ),
    s(
      "Shadow convoy",
      "echo",
      "Three living echoes attack beside you for eight seconds.",
      36,
      { shadows: 3 },
    ),
    s(
      "Assassin's mark",
      "mark",
      "Expose the toughest nearby target and strike its entourage.",
      22,
      { expose: 0.25, count: 4 },
    ),
    s(
      "Echo execution",
      "hunt",
      "Hunt twelve prey; wounded lesser foes take double damage.",
      38,
      { count: 12, execute: true },
    ),
  ],
  volta: [
    s(
      "Arc bridge",
      "hunt",
      "Fork lightning through eight nearby enemies.",
      18,
      { element: "arc", count: 8 },
    ),
    s(
      "Storm pylons",
      "field",
      "Place three lightning pylons that repeatedly shock prey.",
      36,
      { element: "arc", count: 3, chain: true },
    ),
    s(
      "Static bastion",
      "ward",
      "An electric ward blasts prey and recharges your arsenal.",
      24,
      { element: "arc", shield: 24, recover: 1 },
    ),
    s(
      "Discharge field",
      "field",
      "A moving thunder shield restores wards when bolts land.",
      36,
      { element: "arc", follow: true, shieldPulse: 3, chain: true },
    ),
    s(
      "Gravity anchor",
      "pull",
      "Anchor a singularity; drag lesser foes into its pulses.",
      22,
      { element: "vortex", pull: true },
    ),
    s(
      "Rift collapse",
      "meteor",
      "Three delayed collapses stun and crush clustered foes.",
      40,
      { element: "vortex", count: 3, root: 1, radius: 220 },
    ),
  ],
  rook: [
    s(
      "Sunder",
      "fan",
      "Runic stone lances expose a broad line of enemies.",
      18,
      { projectile: "stone", count: 5, expose: 0.15 },
    ),
    s(
      "Seismic march",
      "meteor",
      "Three advancing fault waves fracture the battlefield.",
      34,
      { element: "stone", count: 3, root: 0.8, radius: 200 },
    ),
    s(
      "Guard stance",
      "ward",
      "Fortify your armor, gain a ward and smash nearby prey.",
      24,
      { element: "stone", shield: 26, guard: 0.18 },
    ),
    s(
      "Oath circle",
      "field",
      "An oath follows you; landed shocks replenish your ward.",
      38,
      { element: "stone", shieldPulse: 3, follow: true, root: 0.4 },
    ),
    s(
      "Runic ram",
      "charge",
      "Charge through a crowd and regain poise on impact.",
      20,
      { element: "stone", distance: 220, resource: 0.25 },
    ),
    s(
      "Ruin pillar",
      "field",
      "Raise a seismic pillar that launches repeated stone barrages.",
      36,
      { element: "stone", projectile: "stone", count: 6 },
    ),
  ],
  lumen: [
    s("Lunar fan", "fan", "Piercing moon arrows mark a wide arc of prey.", 18, {
      projectile: "arrow",
      count: 7,
      expose: 0.12,
    }),
    s(
      "Star cascade",
      "meteor",
      "Three falling stars slow prey and refill your focus.",
      34,
      { element: "moon", count: 3, root: 0.6, resource: 0.2 },
    ),
    s(
      "Hunter's gaze",
      "mark",
      "Mark the toughest prey and send moon lances through its pack.",
      20,
      { expose: 0.25, count: 5 },
    ),
    s(
      "Comet lance",
      "beam",
      "A long moon lance pierces the horde and leaves starfire.",
      32,
      { element: "moon", expose: 0.18, radius: 110 },
    ),
    s(
      "Moon ward",
      "ward",
      "A lunar ward repels prey and grants a brief armored veil.",
      24,
      { shield: 24, guard: 0.12, element: "moon" },
    ),
    s(
      "Lunar refuge",
      "field",
      "Stand in moonlight; landed star pulses mend and shield you.",
      38,
      { element: "moon", mend: 0.02, shieldPulse: 2 },
    ),
  ],
  vesper: [
    s(
      "Hex beacon",
      "field",
      "Plant a soul beacon that pulses curses into nearby crowds.",
      20,
      { element: "veil", dot: true },
    ),
    s(
      "Soul implosion",
      "pull",
      "A nether vortex gathers lesser foes and spreads soul blight.",
      36,
      { element: "veil", dot: true, pull: true },
    ),
    s(
      "Imp gate",
      "summon",
      "Open a gate for two temporary imps; demons enter empowered.",
      24,
      { pet: "imp", count: 2, pact: true },
    ),
    s(
      "Demon sentinel",
      "summon",
      "Call an infernal guardian, mend your court and renew its pact.",
      40,
      { pet: "guardian", count: 1, pact: true, petHeal: 0.3 },
    ),
    s(
      "Chaos fan",
      "fan",
      "Piercing soul lances explode around cursed prey.",
      18,
      { projectile: "hex", count: 7, dot: true },
    ),
    s(
      "Nether crossroads",
      "field",
      "Three nether gates curse crowds and call an empowered imp.",
      38,
      { element: "veil", count: 3, dot: true, pet: "imp" },
    ),
  ],
  fen: [
    s(
      "Pack rally",
      "mark",
      "Mark prey, mend your beasts and begin a coordinated hunt.",
      22,
      { count: 6, expose: 0.15, command: true, petHeal: 0.2 },
    ),
    s(
      "Alpha hunt",
      "summon",
      "Two alpha wolves join your commanded pack with wide cleaves.",
      40,
      { pet: "wolf", count: 2, command: true },
    ),
    s(
      "Scatter trap",
      "fan",
      "A piercing crossbow fan pins prey inside a snare.",
      18,
      { projectile: "huntarrow", count: 7, root: 0.8 },
    ),
    s(
      "Stampede",
      "meteor",
      "A spectral pack charges three advancing waves through prey.",
      34,
      { element: "wild", count: 3, radius: 190 },
    ),
    s(
      "Trail snare",
      "trap",
      "Place a trap that roots and marks prey for your beasts.",
      20,
      { root: 1.5, expose: 0.15, element: "wild" },
    ),
    s(
      "Pack refuge",
      "field",
      "A moving refuge mends on landed pulses and renews command.",
      38,
      { follow: true, mend: 0.025, element: "wild", command: true },
    ),
  ],
  solace: [
    s(
      "Radiant verdict",
      "hunt",
      "Smite six prey; landed lances renew a small holy ward.",
      18,
      { count: 6, shieldPulse: 6 },
    ),
    s(
      "Dawn spear",
      "beam",
      "A holy spear pierces crowds; landed light mends and restores faith.",
      32,
      { mend: 0.08, resource: 0.2, element: "holy" },
    ),
    s(
      "Blessed aegis",
      "ward",
      "Raise a holy shield and guard; landed light restores health.",
      24,
      { shield: 28, guard: 0.15, mend: 0.06 },
    ),
    s(
      "Judgment bells",
      "meteor",
      "Three great bells smite and stun lesser prey around you.",
      36,
      { element: "holy", count: 3, radius: 230, root: 0.6 },
    ),
    s(
      "Mercy spring",
      "field",
      "A sacred spring heals its keeper through landed pulses.",
      20,
      { mend: 0.018, element: "holy" },
    ),
    s(
      "Seraph procession",
      "barrage",
      "A moving procession launches holy volleys and mends on smites.",
      38,
      { projectile: "holy", count: 10, mend: 0.02 },
    ),
  ],
  orin: [
    s("Flame idol", "totem", "Renew a fire idol and ignite nearby prey.", 20, {
      totem: "fire",
      element: "fire",
      dot: true,
    }),
    s(
      "Volcanic tide",
      "field",
      "Fire and spirit combine in a spreading volcanic field.",
      36,
      { totem: "fire", element: "fire", count: 3 },
    ),
    s(
      "Thunder beacon",
      "totem",
      "Renew a storm totem and chain lightning through prey.",
      20,
      { totem: "storm", element: "arc", chain: true },
    ),
    s(
      "Tempest relay",
      "field",
      "A moving relay chains lightning and staggers lesser prey.",
      36,
      { element: "arc", chain: true, root: 0.3, follow: true },
    ),
    s(
      "Tide rite",
      "totem",
      "Renew a tide circle and raise a spirit ward.",
      24,
      { totem: "tide", shield: 16, element: "spirit" },
    ),
    s(
      "Spirit merge",
      "summon",
      "An elemental joins the council; all three totems renew.",
      40,
      { pet: "elemental", count: 1, council: true, petHeal: 0.25 },
    ),
  ],
  kestrel: [
    s(
      "Palm fan",
      "fan",
      "Piercing palms strike a wide arc and restore qi on impact.",
      16,
      { projectile: "fist", count: 5, resource: 0.15 },
    ),
    s(
      "Dragon wheel",
      "barrage",
      "A moving jade wheel releases palms and opens serenity.",
      32,
      { projectile: "fist", count: 8, serenity: true },
    ),
    s(
      "Mist step",
      "charge",
      "Flow through foes; landed jade strikes mend the monk.",
      20,
      { distance: 230, mend: 0.05, element: "spirit" },
    ),
    s(
      "Crane chorus",
      "summon",
      "Two spirit cranes join your chorus and raise a jade ward.",
      38,
      { pet: "crane", count: 2, shield: 20 },
    ),
    s(
      "Iron hymn",
      "ward",
      "An iron ward fortifies you and staggers nearby prey.",
      24,
      { shield: 26, guard: 0.18, root: 0.5 },
    ),
    s(
      "Hundred fists",
      "barrage",
      "Repeated heavenly flurries sweep around the moving monk.",
      36,
      { projectile: "fist", count: 12, resource: 0.15 },
    ),
  ],
  morrow: [
    s(
      "Blood grip",
      "pull",
      "Draw lesser foes into a blood field; landed pulses mend you.",
      22,
      { pull: true, mend: 0.02, element: "veil" },
    ),
    s(
      "Crimson march",
      "field",
      "March with a plague wake, a ghoul and renewing runes.",
      38,
      { follow: true, pet: "ghoul", dot: true, resource: 0.1, element: "veil" },
    ),
    s(
      "Rime lance",
      "fan",
      "Piercing rime lances shatter and slow nearby prey.",
      18,
      { projectile: "spirit", count: 5, root: 0.8, element: "frost" },
    ),
    s(
      "Frozen citadel",
      "field",
      "A rime fortress repeatedly staggers lesser foes.",
      36,
      { root: 0.7, shieldPulse: 2, element: "frost" },
    ),
    s(
      "Corpse bloom",
      "trap",
      "A grave rune detonates into spreading plague when prey approach.",
      20,
      { element: "veil", dot: true, radius: 190 },
    ),
    s(
      "Grave call",
      "summon",
      "Two empowered ghouls answer; plague erupts around the legion.",
      40,
      { pet: "ghoul", count: 2, dot: true, element: "veil" },
    ),
  ],
};
const icons = {
  fan: "blade",
  beam: "bolt",
  hunt: "eye",
  meteor: "meteor",
  field: "orbit",
  pull: "orbit",
  ward: "shield",
  charge: "wings",
  blink: "wings",
  mark: "eye",
  trap: "leaf",
  summon: "paw",
  echo: "blade",
  barrage: "star",
  totem: "totem",
};
export const SPELLS = Object.fromEntries(
  Object.entries(rows).flatMap(([hero, spells]) =>
    spells.map((spell, i) => {
      const advanced = i % 2 === 1,
        branch = Math.floor(i / 2),
        id = `${hero}_spell${i}`;
      return [
        id,
        {
          ...spell,
          id,
          hero,
          branch,
          advanced,
          icon: icons[spell.kind],
          masteryId: `${id}_mastery`,
          damage: advanced ? 140 : 90,
          radius: spell.radius || (advanced ? 240 : 175),
          seconds: advanced ? 8 : 5,
          count: spell.count || 6,
        },
      ];
    }),
  ),
);
export const spellsFor = (hero) =>
  Object.values(SPELLS).filter((s) => s.hero === hero);
export function spellMasteryText(spell, rank) {
  const effects = {
    fan: `+${rank} shots · +${rank} pierce`,
    beam: `+${rank * 12}% reach · +${rank * 5}% exposure`,
    hunt: `+${rank * 2} prey · ${rank * 4}% exposure for ${4 + rank * 0.5}s`,
    meteor: `+${rank} impacts`,
    field: `+${rank} pulses · +${rank}s lifetime`,
    pull: `+${rank} pulses · stronger pull`,
    ward: `+${rank * 4} ward · +${rank}s guard`,
    charge: `+${rank * 20} travel · +${rank}s wake`,
    blink: `+${rank * 20} travel · longer echoes`,
    mark: `+${rank * 2} prey · +${rank * 5}% exposure`,
    trap: `+${rank * 0.4}s roots · larger blast`,
    summon: `+${rank * 2}s allies · +${rank * 10}% ally power`,
    echo: `+${rank * 2}s echoes · faster volleys`,
    barrage: `+${rank * 2} shots · +${rank} pulses`,
    totem: `+${rank * 2}s idol · +${rank * 10}% idol power`,
  };
  return `+${rank * 12}% spell power · ${effects[spell.kind]}.`;
}
export const SPELL_SLOTS = [
  { level: 30, bosses: 2, sparks: 8, core: 4, rune: 2, sigil: 0 },
  { level: 75, bosses: 6, sparks: 18, core: 8, rune: 4, sigil: 0 },
  { level: 150, bosses: 12, sparks: 36, core: 12, rune: 8, sigil: 1 },
];
